baseURL: "https://matheusfm.dev/"
defaultContentLanguage: "pt-br"
languageCode: "pt-br"
theme: "LoveIt"
title: "matheusfm"
enableEmoji: true
markup:
  highlight:
    lineNos: true
    noClasses: false

languages:
  pt-br:
    weight: 1
    languageCode: "pt-br"
    languageName: "Português"
    params:
      dateFormat: "02/01/2006"
      section:
        dateFormat: "02/01"
      list:
        dateFormat: "02/01"
      home:
        profile:
          subtitle: "Esse é meu blog sobre tecnologia. "
          enable: true
          gravatarEmail: "matheusfaria.moraes@gmail.com"
          title: ""
          disclaimer: ""
          typeit: true
          social: true
    menu:
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts/"
          weight: 1
        - identifier: "tags"
          name: "Tags"
          url: "/tags/"
          weight: 2
        - identifier: "about"
          name: "Sobre"
          url: "/about/"
          weight: 3
        - identifier: "github"
          pre: "<i class='fab fa-github fa-fw'></i>"
          url: "https://github.com/matheusfm"
          title: "GitHub"
          weight: 4
  en:
    weight: 2
    languageCode: "en"
    languageName: "English"
    params:
      dateFormat: "2006-01-02"
      section:
        dateFormat: "01-02"
      list:
        dateFormat: "01-02"
      home:
        profile:
          subtitle: "This is my blog about technology. "
          enable: true
          gravatarEmail: "matheusfaria.moraes@gmail.com"
          title: ""
          disclaimer: ""
          typeit: true
          social: true
    menu:
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts/"
          weight: 1
        - identifier: "tags"
          name: "Tags"
          url: "/tags/"
          weight: 2
        - identifier: "about"
          name: "About"
          url: "/about/"
          weight: 3
        - identifier: "github"
          pre: "<i class='fab fa-github fa-fw'></i>"
          url: "https://github.com/matheusfm"
          title: "GitHub"
          weight: 4

params:
  version: "0.2.X"
  gitRepo: "https://github.com/matheusfm"
  defaultTheme: "dark"
  search:
    enable: true
    type: "lunr"
  header:
    title:
      name: "matheusfm.dev"
      typeit: true
      pre: ""
      post: ""
  footer:
    enable: true
    hugo: false
    copyright: true
    author: true
    since: 2020
  section: # all posts
    paginate: 20
  list: # category or tag
    paginate: 20
  home:
    posts:
      enable: true
      paginate: 6
  social:
    GitHub: "matheusfm"
    Linkedin: "matheusfm"
    Twitter: "mfariam"
    Email: "matheusfaria.moraes@gmail.com"
  page:
    code:
      copy: true
    share:
      enable: true
      Twitter: true
      Linkedin: true
      Whatsapp: true
    comment:
      enable: true
      utterances:
        enable: true
        repo: "matheusfm/matheusfm.github.io"
        issueTerm: "pathname"
        label: "comment"
        lightTheme: "github-light"
        darkTheme: "github-dark"
  typeit:
    cursorChar: "|"
    duration: -1
  analytics:
    enable: true
    google:
      id: "UA-174922167-1"
      anonymizeIP: true
permalinks:
  posts: ":filename"
author:
  name: "Matheus de Faria Moraes"
  email: "matheusfaria.moraes@gmail.com"
  link: "http://matheusfm.dev"
outputs:
  home:
    - "HTML"
    - "JSON"
